const albums = [
    { "title": "In the Wee Small Hours", "artist": "Frank Sinatra", "year": 1955, "listened": true },

    { "title": "Elvis Presley", "artist": "Elvis Presley", "year": 1956, "listened": true },
    { "title": "Tragic Songs of Life", "artist": "The Louvin Brothers", "year": 1956 },
    { "title": "Songs for Swingin' Lovers", "artist": "Frank Sinatra", "year": 1956 },
    { "title": "The Wildest!", "artist": "Louis Prima Featuring Keely Smith With Sam Butera and the Witnesses", "year": 1956, "listened": true },

    { "title": "Kenya", "artist": "Machito", "year": 1957 },
    { "title": "This is Fats", "artist": "Fats Domino", "year": 1957 },
    { "title": "Ellington at Newport", "artist": "Duke Ellington and his Orchestra", "year": 1957 },
    { "title": "Brilliant Corners", "artist": "Thelonious Monk", "year": 1957 },
    { "title": 'The "Chirping Crickets"', "artist": "The Crickets", "year": 1957 },
    { "title": "Palo Congo", "artist": "Sabu", "year": 1957 },

    { "title": "Lady in Satin", "artist": "Billie Holiday", "year": 1958 },
    { "title": "The Atomic Mr. Basie", "artist": "Count Basie", "year": 1958 },
    { "title": "Bo Diddley/Go Bo Diddley", "artist": "Bo Diddley", "year": 1958 },
    { "title": "Jack Takes the Floor", "artist": "Jack Elliot", "year": 1958 },

    { "title": "Here's Little Richard", "artist": "Little Richard", "year": 1959 },
    { "title": "Time Out", "artist": "The Dave Brubeck Quartet", "year": 1959 },
    { "title": "The Shape of Jazz to Come", "artist": "Ornette Coleman", "year": 1959 },
    { "title": "Mingus Ah Um", "artist": "Charles Mingus", "year": 1959 },
    { "title": "Howling in the Moonlight", "artist": "Howlin' Wolf", "year": 1959 },
    { "title": "Kind of Blue", "artist": "Miles Davis", "listened": true, "year": 1959 },

    { "title": "Sketches of Spain", "artist": "Miles Davis", "year": 1960 },
    { "title": "Giant Steps", "artist": "John Coltrane", "year": 1960 },
    { "title": "Joan Baez", "artist": "Joan Baez", "year": 1960, "listened": true },

    { "title": "At Last!", "artist": "Etta James", "year": 1961 },
    { "title": "Please Mr. Postman", "artist": "The Marvelettes", "year": 1961 },
    { "title": "King of the Delta Blues Singers", "artist": "Robert Johnson", "year": 1961 },

    { "title": "Modern Sounds in Country and Western Music", "artist": "Ray Charles", "year": 1962 },
    { "title": "N°4", "artist": "Serge Gainsbourg", "year": 1962 },
    { "title": "Burnin'", "artist": "John Lee Hooker", "year": 1962 },

    { "title": "Live at the Apollo", "artist": "James Brown", "year": 1963 },
    { "title": "Heat Wave", "artist": "Martha and the Vandellas", "year": 1963 },
    { "title": "The Freewheelin' Bob Dylan", "artist": "Bob Dylan", "year": 1963 },
    { "title": "Meet the Beatles!", "artist": "The Beatles", "year": 1963 },

    { "title": "Hard Day's Night", "artist": "The Beatles", "year": 1964, "listened": true },
    { "title": "Presenting the Fabulous Ronettes", "artist": "The Ronettes", "year": 1964 },
    { "title": "Mary Wells Sings My Guy", "artist": "Mary Wells", "year": 1964 },
    { "title": "Where Did Our Love Go", "artist": "The Supremes", "year": 1964 },

    { "title": "A Love Supreme", "artist": "John Coltrane", "year": 1965 },
    { "title": "More Hits By The Supremes", "artist": "The Supremes", "year": 1965 },
    { "title": "Shotgun", "artist": "Jr. Walker &amp; the All Stars", "year": 1965 },
    { "title": "The Temptations Sing Smokey", "artist": "The Temptations", "year": 1965 },
    { "title": "Help!", "artist": "The Beatles", "year": 1965 },
    { "title": "Dance Party", "artist": "Martha and the Vandellas", "year": 1965 },
    { "title": "Four Tops Second Album", "artist": "The Four Tops", "year": 1965 },
    { "title": "The Beach Boys Today!", "artist": "The Beach Boys", "year": 1965 },
    { "title": "Going to a Go Go", "artist": "Smokey Robinson and the Miracles", "year": 1965 },
    { "title": "Mr. Tambourine Man", "artist": "The Byrds", "year": 1965 },
    { "title": "Live at the Regal", "artist": "B.B. King", "year": 1965 },
    { "title": "Otis Blue", "artist": "Otis Redding", "year": 1965 },
    { "title": "Bringing It All Back Home", "artist": "Bob Dylan", "year": 1965 },
    { "title": "Highway 61 Revisited", "artist": "Bob Dylan", "year": 1965 },
    { "title": "Rubber Soul", "artist": "The Beatles", "year": 1965, "listened": true, "fav": true },

    { "title": "Pet Sounds", "artist": "The Beach Boys", "year": 1966 },
    { "title": "A' Go-Go", "artist": "The Supremes", "year": 1966 },
    { "title": "Fresh Cream", "artist": "Cream", "year": 1966 },
    { "title": "Up-Tight", "artist": "Stevie Wonder", "year": 1966 },
    { "title": "Gettin' Ready", "artist": "The Temptations", "year": 1966 },
    { "title": "Dictionary of Soul", "artist": "Otis Redding", "year": 1966 },
    { "title": "Aftermath", "artist": "The Rolling Stones", "year": 1966 },
    { "title": "Wild Is the Wind", "artist": "Nina Simone", "year": 1966 },
    { "title": "Revolver", "artist": "The Beatles", "year": 1966, "listened": true, "fav": true },
    { "title": "Blonde on Blonde", "artist": "Bob Dylan", "year": 1966 },
    { "title": "Bluesbreakers", "artist": "John Mayall &amp; the Bluesbreakers", "year": 1966, "listened": true },

    { "title": "I Never Loved a Man the Way I Love You", "artist": "Aretha Franklin", "year": 1967 },
    { "title": "The Piper at the Gates of Dawn", "artist": "Pink Floyd", "year": 1967 },
    { "title": "John Wesley Harding", "artist": "Bob Dylan", "year": 1967 },
    { "title": "Higher and Higher", "artist": "Jackie Wilson", "year": 1967 },
    { "title": "Magical Mystery Tour", "artist": "The Beatles", "year": 1967 },
    { "title": "United", "artist": "Marvin Gaye and Tammi Terrell", "year": 1967 },
    { "title": "The Who Sell Out", "artist": "The Who", "year": 1967 },
    { "title": "Wild Honey", "artist": "The Beach Boys", "year": 1967 },
    { "title": "Surrealistic Pillow", "artist": "Jefferson Airplane", "year": 1967 },
    { "title": "Reach Out", "artist": "The Four Tops", "year": 1967 },
    { "title": "Songs of Leonard Cohen", "artist": "Leonard Cohen", "year": 1967 },
    { "title": "I Was Made to Love Her", "artist": "Stevie Wonder", "year": 1967 },
    { "title": "Forever Changes", "artist": "Love", "year": 1967, "listened": true },
    { "title": "Are You Experienced", "artist": "Jimi Hendrix", "year": 1967, "listened": true },
    { "title": "The Doors", "artist": "The Doors", "year": 1967, "listened": true },
    { "title": "Strange Days", "artist": "The Doors", "year": 1967, "listened": true, "fav": true },
    { "title": "Axis: Bold as Love", "artist": "The Jimi Hendrix Experience", "year": 1967, "listened": true },
    { "title": "The Velvet Underground and Nico", "artist": "The Velvet Underground", "year": 1967, "listened": true },
    { "title": "Sgt. Pepper's Lonely Hearts Club Band", "artist": "The Beatles", "year": 1967, "listened": true },
    { "title": "Disraeli Gears", "artist": "Cream", "year": 1967, "listened": true },
    { "title": "Make It Happen/The Tears of a Clown", "artist": "Smokey Robinson and the Miracles", "year": 1967 },

    { "title": "Lady Soul", "artist": "Aretha Franklin", "year": 1968, "listened": true },
    { "title": "Peter Green's Fleetwood Mac", "artist": "Fleetwood Mac", "year": 1968, "listened": true, "fav": true },
    { "title": "Mr. Wonderful", "artist": "Fleetwood Mac", "year": 1968 },
    { "title": "Aretha Now", "artist": "Aretha Franklin", "year": 1968 },
    { "title": "Initials B.B.", "artist": "Serge Gainsbourg", "year": 1968 },
    { "title": "Wheels of Fire", "artist": "Cream", "year": 1968 },
    { "title": "In the Groove", "artist": "Marvin Gaye", "year": 1968 },
    { "title": "You're All I Need", "artist": "Marvin Gaye &amp; Tammi Terrell", "year": 1968 },
    { "title": "For Once In My Life", "artist": "Stevie Wonder", "year": 1968 },
    { "title": "White Album", "artist": "The Beatles", "year": 1968, "listened": true },
    { "title": "Music From Big Pink", "artist": "The Band", "year": 1968, "listened": true },
    { "title": "Waiting for the Sun", "artist": "The Doors", "year": 1968 },
    { "title": "Gris-Gris", "artist": "Dr. John", "year": 1968 },
    { "title": "Eli &amp; the 13th Confession", "artist": "Laura Nyro", "year": 1968, "listened": true },
    { "title": "Something Else by the Kinks", "artist": "The Kinks", "year": 1968 },
    { "title": "White Light/White Heat", "artist": "The Velvet Underground", "year": 1968 },
    { "title": "Sweetheart of the Rodeo", "artist": "The Byrds", "year": 1968 },
    { "title": "Odessey and Oracle", "artist": "The Zombies", "year": 1968 },
    { "title": "Beggars Banquet", "artist": "The Rolling Stones", "year": 1968 },
    { "title": "Electric Ladyland", "artist": "Jimi Hendrix", "year": 1968, "listened": true },
    { "title": "Astral Weeks", "artist": "Van Morrison", "year": 1968 },
    { "title": "At Folsom Prison", "artist": "Johny Cash", "year": 1968 },
    { "title": "Cheap Thrills", "artist": "Big Brother and the Holding Company", "year": 1968, "listened": true },

    { "title": "In the Court of the Crimson King", "artist": "King Crimson", "year": 1969 },
    { "title": "David Bowie", "artist": "David Bowie", "year": 1969 },
    { "title": "Blind Faith", "artist": "Blind Faith", "year": 1969, "listened": true },
    { "title": "Diana Ross Presents the Jackson 5", "artist": "The Jackson 5", "year": 1969 },
    { "title": "The Soft Parade", "artist": "The Doors", "year": 1969 },
    { "title": "Goodbye", "artist": "Cream", "year": 1969 },
    { "title": "From Elvis in Memphis", "artist": "Elvis Presley", "year": 1969 },
    { "title": "Looka Py Py", "artist": "The Meters", "year": 1969 },
    { "title": "Blood, Sweat &amp; Tears", "artist": "Blood, Sweat &amp; Tears", "year": 1969 },
    { "title": "The Stooges", "artist": "The Stooges", "year": 1969 },
    { "title": "The Gilded Palace of Sin", "artist": "The Flying Burrito Brothers", "year": 1969 },
    { "title": "The Kinks Are the Village Green Preservation Society", "artist": "The Kinks", "year": 1969 },
    { "title": "Willy and the Poor Boys", "artist": "Creedence Clearwater Revival", "year": 1969 },
    { "title": "Stand!", "artist": "Sly and the Family Stone", "year": 1969 },
    { "title": "Kick Out the Jams", "artist": "MC5", "year": 1969, "listened": true, "fav": true },
    { "title": "Everybody Knows This Is Nowhere", "artist": "Neil Young", "year": 1969 },
    { "title": "Hot Buttered Soul", "artist": "Isaac Hayes", "year": 1969 },
    { "title": "At San Quentin", "artist": "Johny Cash", "year": 1969, "listened": true },
    { "title": "Led Zeppelin", "artist": "Led Zeppelin", "year": 1969, "listened": true, "fav": true },
    { "title": "Led Zeppelin II", "artist": "Led Zeppelin", "year": 1969, "listened": true, "fav": true },
    { "title": "Tommy", "artist": "The Who", "year": 1969 },
    { "title": "The Velvet Underground", "artist": "The Velvet Underground", "year": 1969 },
    { "title": "Crosby, Stills &amp; Nash", "artist": "Crosby, Stills &amp; Nash", "year": 1969 },
    { "title": "Dusty in Memphis", "artist": "Dusty Springfield", "year": 1969 },
    { "title": "Abbey Road", "artist": "The Beatles", "year": 1969, "listened": true, "fav": true },
    { "title": "The Band", "artist": "The Band", "year": 1969 },
    { "title": "Let It Bleed", "artist": "The Rolling Stones", "year": 1969 },

    { "title": "Led Zeppelin III", "artist": "Led Zeppelin", "year": 1970, "listened": true, "fav": true },
    { "title": "Let It Be", "artist": "The Beatles", "year": 1970, "listened": true },
    { "title": "Curtis", "artist": "Curtis Mayfield", "year": 1970 },
    { "title": "War &amp; Peace", "artist": "Edwin Starr", "year": 1970 },
    { "title": "East Bay Grease", "artist": "Tower of Power", "year": 1970 },
    { "title": "Morrison Hotel", "artist": "The Doors", "year": 1970 },
    { "title": "Workingman's Dead", "artist": "Grateful Dead", "year": 1970 },
    { "title": "Cosmo's Factory", "artist": "Creedence Clearwater Revival", "year": 1970 },
    { "title": "Sex Machine", "artist": "James Brown", "year": 1970 },
    { "title": "The Man Who Sold the World", "artist": "David Bowie", "year": 1970 },
    { "title": "Black Sabbath", "artist": "Black Sabbath", "year": 1970 },
    { "title": "Live at Leeds", "artist": "The Who", "year": 1970 },
    { "title": "Tea for the Tillerman", "artist": "Cat Stevens", "year": 1970 },
    { "title": "American Beauty", "artist": "Grateful Dead", "year": 1970 },
    { "title": "Déjà Vu", "artist": "Crosby, Stills, Nash, and Young", "year": 1970 },
    { "title": "Layla and Other Assorted Love Songs", "artist": "Derek and the Dominos", "year": 1970, "listened": true, "fav": true },
    { "title": "Loaded", "artist": "The Velvet Underground", "year": 1970 },
    { "title": "Moondance", "artist": "Van Morrison", "year": 1970, "listened": true },
    { "title": "Sweet Baby James", "artist": "James Taylor", "year": 1970 },
    { "title": "Paranoid", "artist": "Black Sabbath", "year": 1970, "listened": true, "fav": true },
    { "title": "Bridge Over Troubled Water", "artist": "Simon and Garfunkel", "year": 1970 },
    { "title": "Plastic Ono Band", "artist": "John Lennon", "year": 1970, "listened": true },
    { "title": "All Things Must Pass", "artist": "George Harrison", "year": 1970, "listened": true },
    { "title": "After the Gold Rush", "artist": "Neil Young", "year": 1970 },
    { "title": "Fun House", "artist": "The Stooges", "year": 1970 },
    { "title": "Bitches Brew", "artist": "Miles Davis", "year": 1970 },
    { "title": "Abraxas", "artist": "Santana", "year": 1970 },

    { "title": "Led Zeppelin IV", "artist": "Led Zeppelin", "year": 1971, "listened": true, "fav": true },
    { "title": "L.A. Woman", "artist": "The Doors", "year": 1971, "listened": true, "fav": true },
    { "title": "Pearl", "artist": "Janis Joplin", "year": 1971, "listened": true },
    { "title": "Blue", "artist": "Joni Mitchell", "year": 1971, "listened": true },
    { "title": "I Saw the Light With Some Help From My Friends", "artist": "Earl Scruggs", "year": 1971 },
    { "title": "Coal Miner's Daughter", "artist": "Loretta Lynn", "year": 1971 },
    { "title": "Journey in Satchidanada", "artist": "Alice Coltrane", "year": 1971 },
    { "title": "Ram", "artist": "Paul and Linda McCartney", "year": 1971 },
    { "title": "Just As I Am", "artist": "Bill Withers", "year": 1971 },
    { "title": "Coat of Many Colors", "artist": "Dolly Parton", "year": 1971 },
    { "title": "Nilsson Schmilsson", "artist": "Harry Nilsson", "year": 1971 },
    { "title": "Imagine", "artist": "John Lennon", "year": 1971, "listened": true },
    { "title": "Master of Reality", "artist": "Black Sabbath", "year": 1971 },
    { "title": "Sticky Fingers", "artist": "The Rolling Stones", "year": 1971 },
    { "title": "Maggot Brain", "artist": "Funkadelic", "year": 1971, "listened": true },
    { "title": "John Prine", "artist": "John Prine", "year": 1971 },
    { "title": "Every Picture Tells a Story", "artist": "Rod Stewart", "year": 1971 },
    { "title": "Electric Warrior", "artist": "T. Rex", "year": 1971 },
    { "title": "Hunky Dory", "artist": "David Bowie", "year": 1971 },
    { "title": "What's Going On", "artist": "Marvin Gaye", "year": 1971, "listened": true, "fav": true },
    { "title": "Tapestry", "artist": "Carole King", "year": 1971 },
    { "title": "Who's Next", "artist": "The Who", "year": 1971 },
    { "title": "At Fillmore East", "artist": "The Allman Brothers Band", "year": 1971, "listened": true },
    { "title": "There's a Riot Goin' On", "artist": "Sly and the Family Stone", "year": 1971 },

    { "title": "Exile on Main Street", "artist": "The Rolling Stones", "year": 1972 },
    { "title": "Music Of My Mind", "artist": "Stevie Wonder", "year": 1972 },
    { "title": "Toulouse Street", "artist": "The Doobie Brothers", "year": 1972 },
    { "title": "Nuggets: Original Artyfacts from the First Psychedelic Era", "artist": "Various Artists", "year": 1972 },
    { "title": "Paul Simon", "artist": "Paul Simon", "year": 1972 },
    { "title": "Ege Bamyasi", "artist": "Can", "year": 1972 },
    { "title": "#1 Record", "artist": "Big Star", "year": 1972 },
    { "title": "Close to the Edge", "artist": "Yes", "year": 1972 },
    { "title": "Young, Gifted and Black", "artist": "Aretha Franklin", "year": 1972 },
    { "title": "Something/Anything?", "artist": "Todd Rundgren", "year": 1972 },
    { "title": "I'm Still in Love With You", "artist": "Al Green", "year": 1972 },
    { "title": "Honky Château", "artist": "Elton John", "year": 1972 },
    { "title": "Sail Away", "artist": "Randy Newman", "year": 1972 },
    { "title": "Eagles", "artist": "Eagles", "year": 1972 },
    { "title": "Transformer", "artist": "Lou Reed", "year": 1972 },
    { "title": "Machine Head", "artist": "Deep Purple", "year": 1972, "listened": true, "fav": true },
    { "title": "Made in Japan", "artist": "Deep Purple", "year": 1972, "listened": true, "fav": true },
    { "title": "Amazing Grace", "artist": "Aretha Franklin", "year": 1972 },
    { "title": "Superfly", "artist": "Curtis Mayfield", "year": 1972 },
    { "title": "Harvest", "artist": "Neil Young", "year": 1972 },
    { "title": "Crusaders 1", "artist": "The Crusaders", "year": 1972, "listened": true },
    { "title": "Talking Book", "artist": "Stevie Wonder", "year": 1972 },
    { "title": "Still Bill", "artist": "Bill Withers", "year": 1972 },
    { "title": "Can't Buy a Thrill", "artist": "Steely Dan", "year": 1972, "listened": true },
    { "title": "The Harder They Come: Original Soundtrack", "artist": "Jimmy Cliff and Various Artists", "year": 1972 },
    { "title": "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", "artist": "David Bowie", "year": 1972, "listened": true },

    { "title": "The Dark Side of the Moon", "artist": "Pink Floyd", "year": 1973, "listened": true, "fav": true },
    { "title": "Head Hunters", "artist": "Herbie Hancock", "year": 1973, "listened": true },
    { "title": "Band on the Run", "artist": "Paul McCartney and Wings", "year": 1973, "listened": true },
    { "title": "Houses of the Holy", "artist": "Led Zeppelin", "year": 1973, "listened": true },
    { "title": "The Captain and Me", "artist": "The Doobie Brothers", "year": 1973 },
    { "title": "10cc", "artist": "10cc", "year": 1973 },
    { "title": "Countdown to Ecstasy", "artist": "Steely Dan", "year": 1973, "listened": true },
    { "title": "Mind Games", "artist": "John Lennon", "year": 1973, "listened": true, "fav": true },
    { "title": "Tres Hombres", "artist": "ZZ Top", "year": 1973 },
    { "title": "Aladdin Sane", "artist": "David Bowie", "year": 1973 },
    { "title": "3 + 3", "artist": "The Isley Brothers", "year": 1973 },
    { "title": "For Your Pleasure", "artist": "Roxy Music", "year": 1973 },
    { "title": "Call Me", "artist": "All Green", "year": 1973 },
    { "title": "Let's Get It On", "artist": "Marvin Gaye", "year": 1973 },
    { "title": "(Pronounced 'Leh-nérd 'Skin-'nérd)", "artist": "Lynyrd Skynyrd", "year": 1973 },
    { "title": "New York Dolls", "artist": "New York Dolls", "year": 1973 },
    { "title": "Anthology", "artist": "The Temptations", "year": 1973 },
    { "title": "The Wild, the Innocent &amp; the E Street Shuffle", "artist": "Bruce Springsteen", "year": 1973 },
    { "title": "Goodbye Yellow Brick Road", "artist": "Elton John", "year": 1973 },
    { "title": "Funky Kingston", "artist": "Toots and the Maytals", "year": 1973 },
    { "title": "Catch a Fire", "artist": "Bob Marley and the Wailers", "year": 1973 },
    { "title": "Innervisions", "artist": "Stevie Wonder", "year": 1973 },
    { "title": "Court and Spark", "artist": "Joni Mitchell", "year": 1973 },

    { "title": "Pretzel Logic", "artist": "Steely Dan", "year": 1974, "listened": true, "fav": true },
    { "title": "Red", "artist": "King Crimson", "year": 1974 },
    { "title": "461 Ocean Boulevard", "artist": "Eric Clapton", "year": 1974 },
    { "title": "Apostrophe(')", "artist": "Frank Zappa", "year": 1974, "listened": true },
    { "title": "Walls and Bridges", "artist": "John Lennon", "year": 1974 },
    { "title": "On the Beach", "artist": "Neil Young", "year": 1974 },
    { "title": "Kimono My House", "artist": "Sparks", "year": 1974 },
    { "title": "Diamond Dogs", "artist": "David Bowie", "year": 1974 },
    { "title": "The Grand Tour", "artist": "George Jones", "year": 1974 },
    { "title": "Here Come the Warm Jets", "artist": "Brian Eno", "year": 1974 },
    { "title": "Radio City", "artist": "Big Star", "year": 1974 },
    { "title": "Anthology", "artist": "Diana Ross and the Supremes", "year": 1974 },
    { "title": "I Want to See the Bright Lights Tonight", "artist": "Richard and Linda Thompson", "year": 1974 },

    { "title": "Physical Graffiti", "artist": "Led Zeppelin", "year": 1975, "listened": true },
    { "title": "Young Americans", "artist": "David Bowie", "year": 1975 },
    { "title": "City of Angels", "artist": "The Miracles", "year": 1975 },
    { "title": "Wake Up Everybody", "artist": "Harold Melvin &amp; the Blue Notes", "year": 1975 },
    { "title": "Katy Lied", "artist": "Steely Dan", "year": 1975 },
    { "title": "Another Green World", "artist": "Brian Eno", "year": 1975 },
    { "title": "Ritchie Blackmore's Rainbow", "artist": "Rainbow", "year": 1975, "listened": true, "fav": true },
    { "title": "Greatest Hits", "artist": "Al Green", "year": 1975 },
    { "title": "Forest of Feelings", "artist": "David Sancious", "year": 1975, "listened": true, "fav": true },
    { "title": "Diamonds &amp; Rust", "artist": "Joan Baez", "year": 1975 },
    { "title": "Heart Like a Wheel", "artist": "Linda Ronstadt", "year": 1975 },
    { "title": "Expensive Shit", "artist": "Fela Kuti and Africa 70", "year": 1975 },
    { "title": "That's the Way of the World", "artist": "Earth, Wind and Fire", "year": 1975, "listened": true },
    { "title": "Tonight's the Night", "artist": "Neil Young", "year": 1975 },
    { "title": "Alive!", "artist": "Kiss", "year": 1975 },
    { "title": "The Basement Tapes", "artist": "Bob Dylan and the Band", "year": 1975 },
    { "title": "The Hissing of Summer Lawns", "artist": "Joni Mitchell", "year": 1975 },
    { "title": "Wish You Were Here", "artist": "Pink Floyd", "year": 1975, "listened": true },
    { "title": "Bad Girls", "artist": "Donna Summer", "year": 1975 },
    { "title": "Red Headed Stranger", "artist": "Willie Nelson", "year": 1975 },
    { "title": "A Night at the Opera", "artist": "Queen", "year": 1975 },
    { "title": "Blood on the Tracks", "artist": "Bob Dylan", "year": 1975 },
    { "title": "Born to Run", "artist": "Bruce Springsteen", "year": 1975 },
    { "title": "Horses", "artist": "Patty Smith", "year": 1975 },
    { "title": "Mothership Connection", "artist": "Parliament", "year": 1975 },
    { "title": "Blow By Blow", "artist": "Jeff Beck", "year": 1975, "listened": true },
    { "title": "Fleetwood Mac (the White Album)", "artist": "Fleetwood Mac", "year": 1975 },

    { "title": "The Royal Scam", "artist": "Steely Dan", "year": 1976, "listened": true, "fav": true },
    { "title": "Those Southern Knights", "artist": "The Crusaders", "year": 1976, "listened": true, "fav": true },
    { "title": "Tom Petty &amp; the Heartbreakers", "artist": "Tom Petty and the Heartbreakers", "year": 1976, "listened": true },
    { "title": "Presence", "artist": "Led Zeppelin", "year": 1976 },
    { "title": "Boston", "artist": "Boston", "year": 1976 },
    { "title": "Jaco Pastorius", "artist": "Jaco Pastorius", "year": 1976, "listened": true },
    { "title": "Silk Degrees", "artist": "Boz Scaggs", "year": 1976 },
    { "title": "Rocks", "artist": "Aerosmith", "year": 1976 },
    { "title": "Heavy Weather", "artist": "Weather Report", "year": 1976, "listened": true },
    { "title": "Stuff", "artist": "Stuff", "year": 1976, "listened": true },
    { "title": "The Modern Lovers", "artist": "The Modern Lovers", "year": 1976 },
    { "title": "Hotel California", "artist": "The Eagles", "year": 1976, "listened": true },
    { "title": "Hejira", "artist": "Joni Mitchell", "year": 1976 },
    { "title": "Station to Station", "artist": "David Bowie", "year": 1976 },
    { "title": "The Sun Sessions", "artist": "Elvis Presley", "year": 1976 },
    { "title": "Songs In The Key Of Life", "artist": "Stevie Wonder", "year": 1976 },
    { "title": "2112", "artist": "Rush", "year": 1976 },
    { "title": "Ramones", "artist": "Ramones", "year": 1976 },

    { "title": "Aja", "artist": "Steely Dan", "year": 1977, "listened": true, "fav": true },
    { "title": "Low", "artist": "David Bowie", "year": 1977, "listened": true },
    { "title": "More Stuff", "artist": "Stuff", "year": 1977, "listened": true, "fav": true },
    { "title": "Saturday Night Fever", "artist": "Various Artists", "year": 1977 },
    { "title": "Bat Out Of Hell", "artist": "Meat Loaf", "year": 1977 },
    { "title": "Ahh... The Name Is Bootsy, Baby!", "artist": "Bootsy Collins", "year": 1977 },
    { "title": "Cats on the Coast", "artist": "Sea Level", "year": 1977 },
    { "title": "Lust for Life", "artist": "Iggy Pop", "year": 1977 },
    { "title": "Blondie", "artist": "Blondie", "year": 1977 },
    { "title": '"Heroes"', "artist": "David Bowie", "year": 1977 },
    { "title": "The Idiot", "artist": "Iggy Pop", "year": 1977, "listened": true },
    { "title": "Ask Rufus", "artist": "Rufus, Chaka Khan", "year": 1977 },
    { "title": "Suicide", "artist": "Suicide", "year": 1977 },
    { "title": "Rocket to Russia", "artist": "Ramones", "year": 1977 },
    { "title": "Pink Flag", "artist": "Wire", "year": 1977 },
    { "title": "My Aim is True", "artist": "Elvis Costello", "year": 1977 },
    { "title": "Trans Europe Express", "artist": "Kraftwerk", "year": 1977 },
    { "title": "The Clash", "artist": "The Clash", "year": 1977 },
    { "title": "Marquee Moon", "artist": "Television", "year": 1977 },
    { "title": "Never Mind the Bollocks Here's the Sex Pistols", "artist": "The Sex Pistols", "year": 1977, "listened": true },
    { "title": "Rumours", "artist": "Fleetwood Mac", "year": 1977 },
    { "title": "The Stranger", "artist": "Billy Joel", "year": 1977 },
    { "title": "Exodus", "artist": "Bob Marley and the Wailers", "year": 1977 },
    { "title": "Darkness on the Edge of Town", "artist": "Bruce Springsteen", "year": 1977 },

    { "title": "20 Golden Greats", "artist": "Buddy Holly", "year": 1978 },
    { "title": "Germfree Adolescents", "artist": "X-Ray Spex", "year": 1978 },
    { "title": "Toto", "artist": "Toto", "year": 1978, "listened": true, "fav": true },
    { "title": "Natural High", "artist": "Commodores", "year": 1978 },
    { "title": "Some Girls", "artist": "The Rolling Stones", "year": 1978 },
    { "title": "Here, My Dear", "artist": "Marvin Gaye", "year": 1978 },
    { "title": "More Songs About Buildings and Food", "artist": "Talking Heads", "year": 1978 },
    { "title": "Ambient 1: Music for Airports", "artist": "Brian Eno", "year": 1978, "listened": true },
    { "title": "Q: Are We Not Men? A: We Are Devo!", "artist": "Devo", "year": 1978 },
    { "title": "Third/Sister Lovers", "artist": "Big Star", "year": 1978 },
    { "title": "Van Halen", "artist": "Van Halen", "year": 1978 },
    { "title": "One Nation Under a Groove", "artist": "Funkadelic", "year": 1978 },
    { "title": "This Year's Model", "artist": "Elvis Costello", "year": 1978 },
    { "title": "40 Greatest Hits", "artist": "Hank Williams", "year": 1978 },
    { "title": "Dire Straits", "artist": "Dire Straits", "year": 1978, "listened": true, "fav": true },
    { "title": "Live Stuff", "artist": "Stuff", "year": 1978, "listened": true, "fav": true },
    { "title": "Parallel Lines", "artist": "Blondie", "year": 1978 },

    { "title": "London Calling", "artist": "The Clash", "year": 1979, "listened": true, "fav": true },
    { "title": "The Wall", "artist": "Pink Floyd", "year": 1979, "listened": true, "fav": true },
    { "title": "Communiqué", "artist": "Dire Straits", "year": 1979, "listened": true, "fav": true },
    { "title": "Off the Wall", "artist": "Michael Jackson", "year": 1979, "listened": true },
    { "title": "Stuff It", "artist": "Stuff", "year": 1979, "listened": true },
    { "title": "Ladies' Night", "artist": "Kool &amp; the Gang", "year": 1979, "listened": true },
    { "title": "The B-52's", "artist": "The B-52's", "year": 1979 },
    { "title": "Discovery", "artist": "Electric Light Orchestra", "year": 1979 },
    { "title": "Risqué", "artist": "Chic", "year": 1979 },
    { "title": "Reggatta de Blanc", "artist": "The Police", "year": 1979 },
    { "title": "Hydra", "artist": "Toto", "year": 1979 },
    { "title": "Tusk", "artist": "Fleetwood Mac", "year": 1979 },
    { "title": "Freedom at Point Zero", "artist": "Jefferson Starship", "year": 1979 },
    { "title": "Casiopea", "artist": "Casiopea", "year": 1979 },
    { "title": "The Raincoats", "artist": "The Raincoats", "year": 1979 },
    { "title": "Cut", "artist": "The Slits", "year": 1979 },
    { "title": "Entertainment!", "artist": "Gang of Four", "year": 1979 },
    { "title": "Rust Never Sleeps", "artist": "Neil Young", "year": 1979 },
    { "title": "Street Life", "artist": "The Crusaders", "year": 1979, "listened": true, "fav": true },
    { "title": "Pink Moon", "artist": "Nick Drake", "year": 1979 },
    { "title": "Damn the Torpedoes", "artist": "Tom Petty and the Heartbreakers", "year": 1979 },
    { "title": "Singles Going Steady", "artist": "Buzzcocks", "year": 1979 },

    { "title": "Heaven and Hell", "artist": "Black Sabbath", "year": 1980, "listened": true, "fav": true },
    { "title": "Gaucho", "artist": "Steely Dan", "year": 1980, "listened": true, "fav": true },
    { "title": "Remain in Light", "artist": "Talking Heads", "year": 1980 },
    { "title": "Un autre monde", "artist": "Daniel Balavoine", "year": 1980 },
    { "title": "Beauséjour", "artist": "Michel Berger", "year": 1980 },
    { "title": "Arc of a Diver", "artist": "Steve Winwood", "year": 1980, "listened": true },
    { "title": "McCartney II", "artist": "Paul McCartney", "year": 1980 },
    { "title": "Zenyatta Mondatta", "artist": "The Police", "year": 1980 },
    { "title": "Iron Maiden", "artist": "Iron Maiden", "year": 1980, "listened": true },
    { "title": "Sound Affects", "artist": "The Jam", "year": 1980 },
    { "title": "Los Angeles", "artist": "X", "year": 1980 },
    { "title": "Ace of Spades", "artist": "Motörhead", "year": 1980 },
    { "title": "Scary Monsters (and Super Creeps)", "artist": "David Bowie", "year": 1980 },
    { "title": "Diana", "artist": "Diana Ross", "year": 1980, "listened": true },
    { "title": "Closer", "artist": "Joy Division", "year": 1980 },
    { "title": "Sandinista!", "artist": "The Clash", "year": 1980 },
    { "title": "Unknown Pleasures", "artist": "Joy Division", "year": 1980 },
    { "title": "Dirty Mind", "artist": "Prince", "year": 1980 },
    { "title": "Pretenders", "artist": "The Pretenders", "year": 1980 },
    { "title": "Making Movies", "artist": "Dire Straits", "year": 1980, "listened": true },
    { "title": "Back in Black", "artist": "AC/DC", "year": 1980 },

    { "title": "Fire of Unknown Origin", "artist": "Blue Öyster Cult", "year": 1981 },
    { "title": "Business as Usual", "artist": "Men at Work", "year": 1981 },
    { "title": "Ghost in the Machine", "artist": "The Police", "year": 1981 },
    { "title": "Time", "artist": "Electric Light Orchestra", "year": 1981 },
    { "title": "Killers", "artist": "Iron Maiden", "year": 1981, "listened": true },
    { "title": "Moving Pictures", "artist": "Rush", "year": 1981 },
    { "title": "Damaged", "artist": "Black Flag", "year": 1981 },
    { "title": "Beauty and the Beat", "artist": "The Go-Go's", "year": 1981 },
    { "title": "Never Too Much", "artist": "Luther Vandross", "year": 1981 },
    { "title": "Turn Back", "artist": "Toto", "year": 1981 },
    { "title": "Escape", "artist": "Journey", "year": 1981 },

    { "title": "The Nightfly", "artist": "Donald Fagen", "year": 1982, "listened": true, "fav": true },
    { "title": "Tug of War", "artist": "Paul McCartney", "year": 1982, "listened": true, "fav": true },
    { "title": "The Great Twenty-Eight", "artist": "Chuck Berry", "year": 1982 },
    { "title": "The Number of the Beast", "artist": "Iron Maiden", "year": 1982, "listened": true },
    { "title": "Combat Rock", "artist": "The Clash", "year": 1982 },
    { "title": "1999", "artist": "Prince", "year": 1982 },
    { "title": "The Concert in Central Park", "artist": "Simon &amp; Garfunkel", "year": 1982 },
    { "title": "Avalon", "artist": "Roxy Music", "year": 1982 },
    { "title": "Love over Gold", "artist": "Dire Straits", "year": 1982, "listened": true },
    { "title": "Nebraska", "artist": "Bruce Springsteen", "year": 1982 },
    { "title": "Toto IV", "artist": "Toto", "year": 1982, "listened": true, "fav": true },
    { "title": "Thriller", "artist": "Michael Jackson", "year": 1982, "listened": true },

    { "title": "She's So Unusual", "artist": "Cindy Lauper", "year": 1983 },
    { "title": "Synchronicity", "artist": "The Police", "year": 1983 },
    { "title": "Power, Corruption &amp; Lies", "artist": "New Order", "year": 1983 },
    { "title": "Secret Messages", "artist": "Electric Light Orchestra", "year": 1983 },
    { "title": "Kill 'Em All", "artist": "Metallica", "year": 1983, "listened": true },
    { "title": "Pipes of Peace", "artist": "Paul McCartney", "year": 1983, "listened": true },
    { "title": "Synchronicity", "artist": "The Police", "year": 1983 },
    { "title": "Murmur", "artist": "R.E.M.", "year": 1983 },
    { "title": "Piece of Mind", "artist": "Iron Maiden", "year": 1983, "listened": true },
    { "title": "Let's Dance", "artist": "David Bowie", "year": 1983 },
    { "title": "Run-D.M.C.", "artist": "Run-DMC", "year": 1983 },
    { "title": "Eliminator", "artist": "ZZ Top", "year": 1983, "listened": true, "fav": true },

    { "title": "Purple Rain", "artist": "Prince and the Revolution", "year": 1984 },
    { "title": "Red Hot Chili Peppers", "artist": "Red Hot Chili Peppers", "year": 1984 },
    { "title": "Un autre monde", "artist": "Téléphone", "year": 1984 },
    { "title": "Double Nickels on the Dime", "artist": "Minutemen", "year": 1984 },
    { "title": "Ride the Lightning", "artist": "Metallica", "year": 1984, "listened": true, "fav": true },
    { "title": "Born in the U.S.A.", "artist": "Bruce Springsteen", "year": 1984 },
    { "title": "Let It Be", "artist": "The Replacements", "year": 1984 },
    { "title": "1984", "artist": "Van Halen", "year": 1984, "listened": true },
    { "title": "Powerslave", "artist": "Iron Maiden", "year": 1984, "listened": true, "fav": true },
    { "title": "Diamond Life", "artist": "Sade", "year": 1984 },
    { "title": "Isolation", "artist": "Toto", "year": 1984 },
    { "title": "How Will the Wolf Survive?", "artist": "Los Lobos", "year": 1984 },
    { "title": "Legend", "artist": "Bob Marley and the Wailers", "year": 1984 },

    { "title": "Freaky Styley", "artist": "Red Hot Chili Peppers", "year": 1985, "listened": true, "fav": true },
    { "title": "Hounds of Love", "artist": "Kate Bush", "year": 1985 },
    { "title": "No Jacket Required", "artist": "Phil Collins", "year": 1985 },
    { "title": "Rhythm of the Night", "artist": "DeBarge", "year": 1985 },
    { "title": "We Care a Lot", "artist": "Faith No More", "year": 1985 },
    { "title": "Flash", "artist": "Jeff Beck", "year": 1985 },
    { "title": "The Dream of the Blue Turtles", "artist": "Sting", "year": 1985 },
    { "title": "Rain Dogs", "artist": "Tom Waits", "year": 1985 },
    { "title": "The Indestructible Beat of Soweto", "artist": "Various Artists", "year": 1985 },
    { "title": "New Day Rising", "artist": "Hüsker Dü", "year": 1985 },
    { "title": "Live at the Harlem Square Club, 1963", "artist": "Sam Cooke", "year": 1985 },
    { "title": "Whitney Houston", "artist": "Whitney Houston", "year": 1985 },
    { "title": "Brothers in Arms", "artist": "Dire Straits", "year": 1985, "listened": true },

    { "title": "Master Of Puppets", "artist": "Metallica", "year": 1986, "listened": true },
    { "title": "Somewhere in Time", "artist": "Iron Maiden", "year": 1986, "listened": true, "fav": true },
    { "title": "So", "artist": "Peter Gabriel", "year": 1986 },
    { "title": "Slippery When Wet", "artist": "Bon Jovi", "year": 1986 },
    { "title": "Fahrenheit", "artist": "Toto", "year": 1986 },
    { "title": "Rapture", "artist": "Anita Baker", "year": 1986 },
    { "title": "Raising Hell", "artist": "Run-DMC", "year": 1986 },
    { "title": "Control", "artist": "Janet Jackson", "year": 1986 },
    { "title": "The Queen Is Dead", "artist": "The Smiths", "year": 1986 },
    { "title": "Graceland", "artist": "Paul Simon", "year": 1986 },
    { "title": "Licensed to Ill", "artist": "Beastie Boys", "year": 1986 },
    { "title": "Paid in Full", "artist": "Eric B. and Rakim", "year": 1986 },

    { "title": "Plâtre et ciment", "artist": "Jean-Louis Aubert", "year": 1987 },
    { "title": "Tango in the Night", "artist": "Fleetwood Mac", "year": 1987, "listened": true, "fav": true },
    { "title": "Sign O' the Times", "artist": "Prince", "year": 1987 },
    { "title": "Hysteria", "artist": "Def Leppard", "year": 1987 },
    { "title": "...Noting Like the Sun", "artist": "Sting", "year": 1987 },
    { "title": "Introduce Yourself", "artist": "Faith No More", "year": 1987 },
    { "title": "Criminal Minded", "artist": "Boogie Down Productions", "year": 1987 },
    { "title": "The Joshua Tree", "artist": "U2", "year": 1987 },
    { "title": "Pet Shop Boys", "artist": "Actually", "year": 1987 },
    { "title": "Faith", "artist": "George Michael", "year": 1987, "listened": true },
    { "title": "Bad", "artist": "Michael Jackson", "year": 1987 },
    { "title": "The Uplift Mofo Party Plan", "artist": "Red Hot Chili Peppers", "year": 1987, "listened": true },
    { "title": "Appetite for Destruction", "artist": "Guns N' Roses", "year": 1987, "listened": true, "fav": true },

    { "title": "It Takes A Nation Of Millions To Hold Us Back", "artist": "Public Enemy", "year": 1988 },
    { "title": "Tracy Chapman", "artist": "Tracy Chapman", "year": 1988 },
    { "title": "Lucinda Williams", "artist": "Lucinda Williams", "year": 1988 },
    { "title": "Surfer Rosa", "artist": "Pixies", "year": 1988 },
    { "title": "Seventh Son of a Seventh Son", "artist": "Iron Maiden", "year": 1988, "listened": true },
    { "title": "The Seventh One", "artist": "Toto", "year": 1988 },
    { "title": "Daydream Nation", "artist": "Sonic Youth", "year": 1988 },
    { "title": "Straight Outta Compton", "artist": "N.W.A.", "year": 1988 },
    { "title": "...And Justice for All", "artist": "Metallica", "year": 1988, "listened": true, "fav": true },

    { "title": "Bleu Blanc Vert", "artist": "Jean-Louis Aubert", "year": 1989 },
    { "title": "Mother's Milk", "artist": "Red Hot Chili Peppers", "year": 1989 },
    { "title": "Paul's Boutique", "artist": "Beastie Boys", "year": 1989 },
    { "title": "The Real Thing", "artist": "Faith No More", "year": 1989, "listened": true },
    { "title": "The Stones Roses", "artist": "The Stone Roses", "year": 1989 },
    { "title": "Like a Prayer", "artist": "Madonna", "year": 1989 },
    { "title": "Pretty Hate Machine", "artist": "Nine Inch Nails", "year": 1989 },
    { "title": "Nick of Time", "artist": "Bonnie Raitt", "year": 1989 },
    { "title": "The Offspring", "artist": "The Offspring", "year": 1989, "listened": true },
    { "title": "Full Moon Fever", "artist": "Tom Petty", "year": 1989 },
    { "title": "Rhythm Nation 1814", "artist": "Janet Jackson", "year": 1989 },
    { "title": "Veuillez rendre l'âme (à qui elle appartient)", "artist": "Noir Désir", "year": 1989 },
    { "title": "Three Feet High and Rising", "artist": "De La Soul", "year": 1989 },
    { "title": "Disintegration", "artist": "The Cure", "year": 1989 },
    { "title": "Doolittle", "artist": "Pixies", "year": 1989 },

    { "title": "Violator", "artist": "Depeche Mode", "year": 1990 },
    { "title": "No Fences", "artist": "Garth Brooks", "year": 1990 },
    { "title": "Sentinelles", "artist": "Axel Bauer", "year": 1990 },
    { "title": "Pornograffiti", "artist": "Extreme", "year": 1990, "listened": true, "fav": true },
    { "title": "Heaven or Las Vegas", "artist": "Cocteau Twins", "year": 1990 },
    { "title": "No Prayer for the Dying", "artist": "Iron Maiden", "year": 1990 },
    { "title": "Goo", "artist": "Sonic Youth", "year": 1990 },
    { "title": "I Do Not Want What I Haven't Got", "artist": "Sinéad O'Connor", "year": 1990 },
    { "title": "The Immaculate Collection", "artist": "Madonna", "year": 1990 },
    { "title": "Fear of a Black Planet", "artist": "Public Enemy", "year": 1990 },
    { "title": "AmeriKKKa's Most Wanted", "artist": "Ice Cube", "year": 1990 },

    { "title": "Innuendo", "artist": "Queen", "year": 1991, "listened": true, "fav": true },
    { "title": "The Low End Theory", "artist": "A Tribe Called Quest", "year": 1991 },
    { "title": "The Birth of Soul", "artist": "Ray Charles", "year": 1991 },
    { "title": "The Soul Cages", "artist": "Sting", "year": 1991 },
    { "title": "Back to Mono (1958-1969)", "artist": "Phil Spector and Various Artists", "year": 1991 },
    { "title": "Screamadelica", "artist": "Primal Scream", "year": 1991 },
    { "title": "First Take", "artist": "Roberta Flack", "year": 1991 },
    { "title": "De La Soul Is Dead", "artist": "De La Soul", "year": 1991 },
    { "title": "Proud Mary: The Best of Ike and Tina Turner", "artist": "Ike and Tina Turner", "year": 1991 },
    { "title": "Blue Lines", "artist": "Massive Attack", "year": 1991 },
    { "title": "Du ciment sous les plaines", "artist": "Noir Désir", "year": 1991 },
    { "title": "Metallica", "artist": "Metallica", "year": 1991 },
    { "title": "Achtung Baby", "artist": "U2", "year": 1991 },
    { "title": "II", "artist": "Boyz II Men", "year": 1991 },
    { "title": "On Every Street", "artist": "Dire Straits", "year": 1991, "listened": true },
    { "title": "Ten", "artist": "Pearl Jam", "year": 1991 },
    { "title": "Star Time", "artist": "James Brown", "year": 1991 },
    { "title": "Blood Sugar Sex Magik", "artist": "Red Hot Chili Peppers", "year": 1991, "listened": true, "fav": true },
    { "title": "Loveless", "artist": "My Bloody Valentine", "year": 1991 },
    { "title": "Mama Said Knock You Out", "artist": "LL Cool J", "year": 1991 },
    { "title": "Nevermind", "artist": "Nirvana", "year": 1991, "listened": true },

    { "title": "Tostaky", "artist": "Noir Désir", "year": 1992, "listened": true },
    { "title": "Ignition", "artist": "The Offspring", "year": 1992, "listened": true },
    { "title": "Rage Against the Machine", "artist": "Rage Against the Machine", "year": 1992, "listened": true, "fav": true },
    { "title": "The Chronic", "artist": "Dr. Dre", "year": 1992 },
    { "title": "No Doubt", "artist": "No Doubt", "year": 1992 },
    { "title": "Angel Dust", "artist": "Faith No More", "year": 1992, "listened": true },
    { "title": "Fear of the Dark", "artist": "Iron Maiden", "year": 1992, "listened": true },
    { "title": "Kingdom of Desire", "artist": "Toto", "year": 1992 },
    { "title": "Bizarre Ride II the Pharcyde", "artist": "The Pharcyde", "year": 1992 },
    { "title": "Check Your Head", "artist": "Beastie Boys", "year": 1992 },
    { "title": "What's the 411?", "artist": "Mary J. Blige", "year": 1992 },
    { "title": "Little Earthquakes", "artist": "Tori Amos", "year": 1992 },
    { "title": "Love Deluxe", "artist": "Sade", "year": 1992 },
    { "title": "In the Hell of Patchinko", "artist": "Mano Negra", "year": 1992, "fav": true, "listened": true },
    { "title": "Automatic for the People", "artist": "R.E.M.", "year": 1992 },

    { "title": "Emergency on Planet Earth", "artist": "Jamiroquai", "year": 1993, "listened": true, "fav": true },
    { "title": "Kamakiriad", "artist": "Donald Fagen", "year": 1993 },
    { "title": "Enter the Wu-Tang (36 Chambers)", "artist": "Wu-Tang Clan", "year": 1993 },
    { "title": "C'est déjà ça", "artist": "Alain Souchon", "year": 1993 },
    { "title": "All Killer No Filler!", "artist": "Jerry Lee Lewis", "year": 1993 },
    { "title": "Siamese Dream", "artist": "The Smashing Pumpkins", "year": 1993 },
    { "title": "Rid of Me", "artist": "PJ Harvey", "year": 1993 },
    { "title": "Doggystyle", "artist": "Snoop Doggy Dogg", "year": 1993 },
    { "title": "In Utero", "artist": "Nirvana", "year": 1993 },
    { "title": "Midnight Marauders", "artist": "A Tribe Called Quest", "year": 1993 },
    { "title": "Slanted and Enchanted", "artist": "Pavement", "year": 1993 },
    { "title": "Exile in Guyville", "artist": "Liz Phair", "year": 1993 },
    { "title": "Last Splash", "artist": "The Breeders", "year": 1993 },

    { "title": "The Return of the Space Cowboy", "artist": "Jamiroquai", "year": 1994, "listened": true, "fav": true },
    { "title": "Stoner Witch", "artist": "The Melvins", "year": 1994, "listened": true, "fav": true },
    { "title": "Dummy", "artist": "Portishead", "year": 1994, "listened": true },
    { "title": "11 Tracks of Wack", "artist": "Walter Becker", "year": 1994, "listened": true },
    { "title": "Smash", "artist": "The Offspring", "year": 1994, "listened": true },
    { "title": "My Life", "artist": "Mary J. Blige", "year": 1994 },
    { "title": "Cracked Rear View", "artist": "Hootie &amp; the Blowfish", "year": 1994 },
    { "title": "Superunknown", "artist": "Soundgarden", "year": 1994 },
    { "title": "From the Cradle", "artist": "Eric Clapton", "year": 1994 },
    { "title": "Emmerdale", "artist": "The Cardigans", "year": 1994, "listened": true },
    { "title": "Parklife", "artist": "Blur", "year": 1994, "listened": true, "fav": true },
    { "title": "Amor Prohibido", "artist": "Selena", "year": 1994 },
    { "title": "Crooked Rain, Crooked Rain", "artist": "Pavement", "year": 1994 },
    { "title": "Dookie", "artist": "Green Day", "year": 1994 },
    { "title": "Weezer", "artist": "Weezer", "year": 1994 },
    { "title": "Wildflowers", "artist": "Tom Petty", "year": 1994 },
    { "title": "CrazySexyCool", "artist": "TLC", "year": 1994 },
    { "title": "Definitely Maybe", "artist": "Oasis", "year": 1994, "listened": true },
    { "title": "Live Through This", "artist": "Hole", "year": 1994 },
    { "title": "MTV Unplugged in New York", "artist": "Nirvana", "year": 1994, "listened": true },
    { "title": "The Downward Spiral", "artist": "Nine Inch Nails", "year": 1994 },
    { "title": "Ready to Die", "artist": "The Notorious B.I.G.", "year": 1994 },
    { "title": "Illmatic", "artist": "Nas", "year": 1994 },
    { "title": "Grace", "artist": "Jeff Buckley", "year": 1994 },

    { "title": "Life", "artist": "The Cardigans", "year": 1995 },
    { "title": "The Rhythm of the Night", "artist": "Corona", "year": 1995 },
    { "title": "Liquid Swords", "artist": "GZA", "year": 1995 },
    { "title": "King for a Day... Fool for a Lifetime", "artist": "Faith No More", "year": 1995, "listened": true },
    { "title": "Tambu", "artist": "Toto", "year": 1995 },
    { "title": "The Infamous", "artist": "Mobb Deep", "year": 1995 },
    { "title": "Wowee Zowee", "artist": "Pavement", "year": 1995 },
    { "title": "The Bends", "artist": "Radiohead", "year": 1995, "listened": true },
    { "title": "Post", "artist": "Björk", "year": 1995 },
    { "title": "Only Built 4 Cuban Linx", "artist": "Raekwon", "year": 1995 },
    { "title": "(What's the Story) Morning Glory?", "artist": "Oasis", "year": 1995 },
    { "title": "Different Class", "artist": "Pulp", "year": 1995 },
    { "title": "Brown Sugar", "artist": "D'Angelo", "year": 1995 },
    { "title": "Jagged Little Pill", "artist": "Alanis Morissette", "year": 1995 },
    { "title": "Mellon Collie and the Infinite Sadness", "artist": "The Smashing Pumpkins", "year": 1995, "listened": true },

    { "title": "Travelling Without Moving", "artist": "Jamiroquai", "year": 1996, "listened": true, "fav": true },
    { "title": "Stag", "artist": "The Melvins", "year": 1996, "listened": true, "fav": true },
    { "title": "Endtroducing...", "artist": "DJ Shadow", "year": 1996, "listened": true },
    { "title": "Down Every Road 1962-1994", "artist": "Merle Haggard", "year": 1996 },
    { "title": "All Eyez on Me", "artist": "2Pac", "year": 1996 },
    { "title": "Falling Into You", "artist": "Céline Dion", "year": 1996 },
    { "title": "Odelay", "artist": "Beck", "year": 1996 },
    { "title": "First Band on the Moon", "artist": "The Cardigans", "year": 1996 },
    { "title": "Sheryl Crow", "artist": "Sheryl Crow", "year": 1996 },
    { "title": "If You're Feeling Sinister", "artist": "Belle and Sebastian", "year": 1996 },
    { "title": "666.667 Club", "artist": "Noir Désir", "year": 1996, "listened": true },
    { "title": "The Score", "artist": "Fugees", "year": 1996 },
    { "title": "Evil Empire", "artist": "Rage Against the Machine", "year": 1996, "listened": true, "fav": true },
    { "title": "Load", "artist": "Metallica", "year": 1996 },
    { "title": "One in a Million", "artist": "Aaliyah", "year": 1996 },
    { "title": "Reasonable Doubt", "artist": "Jay-Z", "year": 1996 },

    { "title": "Either/Or", "artist": "Elliott Smith", "year": 1997 },
    { "title": "Let's Talk About Love", "artist": "Céline Dion", "year": 1997 },
    { "title": "Louise Attaque", "artist": "Louise Attaque", "year": 1997, "listened": true },
    { "title": "Sehnsucht", "artist": "Rammstein", "year": 1997 },
    { "title": "Homework", "artist": "Daft Punk", "year": 1997, "listened": true, "fav": true },
    { "title": "Dig Your Own Hole", "artist": "The Chemical Brothers", "year": 1997, "listened": true },
    { "title": "Shadow of the Moon", "artist": "Blackmore's Night", "year": 1997, "listened": true },
    { "title": "Tellin' Stories", "artist": "The Charlatans", "year": 1997 },
    { "title": "It's My Life", "artist": "Sash!", "year": 1997 },
    { "title": "Earthling", "artist": "David Bowie", "year": 1997 },
    { "title": "The Velvet Rope", "artist": "Janet Jackson", "year": 1997 },
    { "title": "I Can Hear the Heart Beating As One", "artist": "Yo La Tengo", "year": 1997 },
    { "title": "Ixnay on the Hombre", "artist": "The Offspring", "year": 1997, "listened": true, "fav": true },
    { "title": "Flaming Pie", "artist": "Paul McCartney", "year": 1997, "listened": true, "fav": true },
    { "title": "Homogenic", "artist": "Björk", "year": 1997 },
    { "title": "f&#9839; A&#9839; &infin;", "artist": "Godspeed You! Black Emperor", "year": 1997 },
    { "title": "Life After Death", "artist": "The Notorious B.I.G.", "year": 1997 },
    { "title": "OK Computer", "artist": "Radiohead", "year": 1997, "listened": true, "fav": true },
    { "title": "ReLoad", "artist": "Metallica", "year": 1997 },
    { "title": "Supa Dupa Fly", "artist": "Missy Elliott", "year": 1997 },
    { "title": "Baduizm", "artist": "Erykah Badu", "year": 1997 },
    { "title": "Come on Over", "artist": "Shania Twain", "year": 1997 },
    { "title": "Dig Me Out", "artist": "Sleater-Kinney", "year": 1997 },
    { "title": "Buena Vista Social Club", "artist": "Buena Vista Social Club", "year": 1997 },

    { "title": "Symphony of Enchanted Lands", "artist": "Rhapsody", "year": 1998 },
    { "title": "System Of A Down", "artist": "System Of A Down", "year": 1998 },
    { "title": "Queens of the Stone Age", "artist": "Queens of the Stone Age", "year": 1998, "listened": true, "fav": true },
    { "title": "Mezzanine", "artist": "Massive Attack", "year": 1998 },
    { "title": "Pilgrim", "artist": "Eric Clapton", "year": 1998 },
    { "title": "Follow the Leader", "artist": "Korn", "year": 1998, "listened": true },
    { "title": "A Go Go", "artist": "John Scofield", "year": 1998, "listened": true },
    { "title": "Gran Turismo", "artist": "The Cardigans", "year": 1998, "listened": true, "fav": true },
    { "title": "Dònde Estàn los Ladrones", "artist": "Shakira", "year": 1998 },
    { "title": "Hellbilly Deluxe", "artist": "Rob Zombie", "year": 1998 },
    { "title": "SUPER EUROBEAT presents INITIAL D ~D SELECTION~", "artist": "Various Artists", "year": 1998 },
    { "title": "Americana", "artist": "The Offspring", "year": 1998, "listened": true, "fav": true },
    { "title": "Ray of Light", "artist": "Madonna", "year": 1998 },
    { "title": "Aquemini", "artist": "OutKast", "year": 1998 },
    { "title": "400 Degreez", "artist": "Juvenile", "year": 1998 },
    { "title": "Clandestino", "artist": "Manu Chao", "year": 1998 },
    { "title": "Car Wheels on a Gravel Road", "artist": "Lucinda Williams", "year": 1998 },
    { "title": "The Miseducation of Lauryn Hill", "artist": "Lauren Hill", "year": 1998 },
    { "title": "One Trip/One Noise", "artist": "Noir Désir", "year": 1998, "listened": true, "fav": true },
    { "title": "Moon Safari", "artist": "Air", "year": 1998, "fav": true, "listened": true },
    { "title": "In the Aeroplane Over The Sea", "artist": "Neutral Milk Hotel", "year": 1998, "listened": true },
    { "title": "Music has the right to children", "artist": "Boards of Canada", "year": 1998 },
    { "title": "When the Pawn...", "artist": "Fiona Apple", "year": 1998 },

    { "title": "Synkronized", "artist": "Jamiroquai", "year": 1999, "listened": true, "fav": true },
    { "title": "Fly", "artist": "Dixie Chicks", "year": 1999 },
    { "title": "Millennium", "artist": "Backstreet Boys", "year": 1999 },
    { "title": "Supernatural", "artist": "Santana", "year": 1999 },
    { "title": "Je Dis Aime", "artist": "-M-", "year": 1999 },
    { "title": "Mindfields", "artist": "Toto", "year": 1999 },
    { "title": "Significant Other", "artist": "Limp Bizkit", "year": 1999, "listened": true },
    { "title": "The Man Who", "artist": "Travis", "year": 1999 },
    { "title": "Under a Violet Moon", "artist": "Blackmore's Night", "year": 1999, "listened": true },
    { "title": "Kaleidoscope", "artist": "Kelis", "year": 1999 },
    { "title": "69 Love Songs", "artist": "Magnetic Fields", "year": 1999 },
    { "title": "...Baby One More Time", "artist": "Britney Spears", "year": 1999 },
    { "title": "Things Fall Apart", "artist": "The Roots", "year": 1999 },
    { "title": "The Slim Shady LP", "artist": "Eminem", "year": 1999 },
    { "title": "Californication", "artist": "Red Hot Chili Peppers", "year": 1999, "listened": true },
    { "title": "The Writing's on the Wall", "artist": "Destiny's Child", "year": 1999 },
    { "title": "The Battle of Los Angeles", "artist": "Rage Against the Machine", "year": 1999, "listened": true },
    { "title": "Enema of the State", "artist": "Blink-182", "year": 1999 },
    { "title": "Slipknot", "artist": "Slipknot", "year": 1999 },
    { "title": "Au ras des pâquerettes", "artist": "Alain Souchon", "year": 1999 },

    { "title": "Tony Hawk Pro Skater 2 OST", "artist": "Various Artists", "year": 2000, "listened": true, "fav": true },
    { "title": "Dawn of Victory", "artist": "Rhapsody", "year": 2000 },
    { "title": "No Strings Attached", "artist": "NSYNC", "year": 2000 },
    { "title": "Oops!... I Did It Again", "artist": "Britney Spears", "year": 2000 },
    { "title": "Personne n'est parfait", "artist": "Axel Bauer", "year": 2000 },
    { "title": "Kid A", "artist": "Radiohead", "year": 2000 },
    { "title": "Riding with the King", "artist": "Eric Clapton and B.B. King", "year": 2000, "listened": true },
    { "title": "Hybrid Theory", "artist": "Linkin Park", "year": 2000 },
    { "title": "Two Against Nature", "artist": "Steely Dan", "year": 2000 },
    { "title": "Conspiracy of One", "artist": "The Offspring", "year": 2000, "listened": true, "fav": true },
    { "title": "The Ultimate Collection", "artist": "Patsy Cline", "year": 2000 },
    { "title": "Sailing to Philadelphia", "artist": "Mark Knopfler", "year": 2000, "listened": true, "fav": true },
    { "title": "The Marshall Mathers LP", "artist": "Eminem", "year": 2000 },
    { "title": "Mama's Gun", "artist": "Erykah Badu", "year": 2000 },
    { "title": "Voodoo", "artist": "D'Angelo", "year": 2000 },
    { "title": "Supreme Clientele", "artist": "Ghostface Killah", "year": 2000 },
    { "title": "Stankonia", "artist": "OutKast", "year": 2000 },
    { "title": "Stories From the City, Stories From the Sea", "artist": "PJ Harvey", "year": 2000 },

    { "title": "A Funk Odyssey", "artist": "Jamiroquai", "year": 2001, "fav": true, "listened": true },
    { "title": "Discovery", "artist": "Daft Punk", "year": 2001, "fav": true, "listened": true },
    { "title": "Gorillaz", "artist": "Gorillaz", "year": 2001, "fav": true, "listened": true },
    { "title": "Toxicity", "artist": "System Of A Down", "year": 2001, "fav": true, "listened": true },
    { "title": "Is this it", "artist": "The Strokes", "year": 2001 },
    { "title": "Mutter", "artist": "Rammstein", "year": 2001 },
    { "title": "Rain of a Thousand Flames", "artist": "Rhapsody", "year": 2001 },
    { "title": "Iowa", "artist": "Slipknot", "year": 2001 },
    { "title": "Reptile", "artist": "Eric Clapton", "year": 2001 },
    { "title": "All Killer No Filler", "artist": "Sum 41", "year": 2001 },
    { "title": "Modjo", "artist": "Modjo", "year": 2001, "listened": true },
    { "title": "Origin of Symmetry", "artist": "Muse", "year": 2001, "listened": true },
    { "title": "The Anthology", "artist": "Muddy Waters", "year": 2001 },
    { "title": "Love and Theft", "artist": "Bob Dylan", "year": 2001 },
    { "title": "The Definite Collection", "artist": "ABBA", "year": 2001 },
    { "title": "Time (The Revelator)", "artist": "Gillian Welch", "year": 2001 },
    { "title": "Yankee Hotel Foxtrot", "artist": "Wilco", "year": 2001 },
    { "title": "Des visages des figures", "artist": "Noir Désir", "year": 2001, "listened": true, "fav": true },
    { "title": "Since I Left You", "artist": "The Avalanches", "year": 2001, "listened": true },
    { "title": "The Blueprint", "artist": "Jay-Z", "year": 2001 },
    { "title": "White Blood Cells", "artist": "The White Stripes", "year": 2001 },
    { "title": "Get Rich or Die Tryin'", "artist": "50 Cent", "year": 2001 },
    { "title": "Fires at Midnight", "artist": "Blackmore's Night", "year": 2001 },

    { "title": "Power of the Dragonflame", "artist": "Rhapsody", "year": 2002, "listened": true },
    { "title": "Come Away With Me", "artist": "Norah Jones", "year": 2002, "listened": true },
    { "title": "The Eminem Show", "artist": "Eminem", "year": 2002, "listened": true, "fav": true },
    { "title": "Songs for the Deaf", "artist": "Queens of the Stone Age", "year": 2002, "listened": true, "fav": true },
    { "title": "Morrowind OST", "artist": "Jeremy Soule", "year": 2002, "listened": true, "fav": true },
    { "title": "By The Way", "artist": "Red Hot Chili Peppers", "year": 2002, "listened": true },
    { "title": "A Rush of Blood to the Head", "artist": "Coldplay", "year": 2002 },
    { "title": "Laika Come Home", "artist": "Gorillaz", "year": 2002 },
    { "title": "Does This Look Infected?", "artist": "Sum 41", "year": 2002 },
    { "title": "Steal This Album!", "artist": "System Of A Down", "year": 2002, "listened": true },

    { "title": "De-Loused in the Comatorium", "artist": "The Mars Volta", "year": 2003 },
    { "title": "Qui de nous deux", "artist": "-M-", "year": 2003 },
    { "title": "3.6.3 (Live 2003)", "artist": "Indochine", "year": 2003, "listened": true, "fav": true },
    { "title": "Live in Texas", "artist": "Linkin Park", "year": 2003, "listened": true, "fav": true },
    { "title": "Everything Must Go", "artist": "Steely Dan", "year": 2003, "listened": true },
    { "title": "Splinter", "artist": "The Offspring", "year": 2003, "listened": true, "fav": true },
    { "title": "The Diary of Alicia Keys", "artist": "Alicia Keys", "year": 2003 },
    { "title": "Ghost of a Rose", "artist": "Blackmore's Night", "year": 2003 },
    { "title": "Sleeping with Ghosts", "artist": "Placebo", "year": 2003 },
    { "title": "Reality", "artist": "David Bowie", "year": 2003 },
    { "title": "Fever to Tell", "artist": "Yeah Yeah Yeahs", "year": 2003 },
    { "title": "The Best of the Classic Years", "artist": "King Sunny Adé", "year": 2003 },
    { "title": "Speakerboxxx/The Love Below", "artist": "OutKast", "year": 2003 },
    { "title": "St. Anger", "artist": "Metallica", "year": 2003, "listened": true },
    { "title": "Portrait of a Legend", "artist": "Sam Cooke", "year": 2003 },
    { "title": "The Black Album", "artist": "Jay-Z", "year": 2003 },
    { "title": "Elephant", "artist": "The White Stripes", "year": 2003, "listened": true, "fav": true },

    { "title": "Symphony of Enchanted Lands II (The Dark Secret)", "artist": "Rhapsody of Fire", "year": 2004, "listened": true, "fav": true },
    { "title": "The College Dropout", "artist": "Kanye West", "year": 2004 },
    { "title": "She's in Control", "artist": "Chromeo", "year": 2004, "listened": true },
    { "title": "Franz Ferdinand", "artist": "Franz Ferdinand", "year": 2004 },
    { "title": "Musicology", "artist": "Prince", "year": 2004 },
    { "title": "Vol.3: The Subliminal Verses", "artist": "Slipknot", "year": 2004 },
    { "title": "Absolution", "artist": "Muse", "year": 2004, "listened": true, "fav": true },
    { "title": "Ratatat", "artist": "Ratatat", "year": 2004, "listened": true, "fav": true },
    { "title": "Reise, Reise", "artist": "Rammstein", "year": 2004 },
    { "title": "Smile", "artist": "Brian Wilson", "year": 2004 },
    { "title": "Interzone", "artist": "Serge Teyssot-Gay", "year": 2004 },
    { "title": "Confessions", "artist": "Usher", "year": 2004 },
    { "title": "Barrio Fino", "artist": "Daddy Yankee", "year": 2004 },
    { "title": "Madvillainy", "artist": "Madvillain", "year": 2004 },
    { "title": "Funeral", "artist": "Arcade Fire", "year": 2004 },
    { "title": "American Idiot", "artist": "Green Day", "year": 2004, "listened": true },

    { "title": "Dynamite", "artist": "Jamiroquai", "year": 2005, "fav": true, "listened": true },
    { "title": "Mezmerize", "artist": "System Of A Down", "year": 2005, "fav": true, "listened": true },
    { "title": "Hypnotize", "artist": "System Of A Down", "year": 2005, "listened": true },
    { "title": "Lullabies To Paralyze", "artist": "Queens of the Stone Age", "year": 2005, "listened": true, "fav": true },
    { "title": "Human After All", "artist": "Daft Punk", "year": 2005, "fav": true, "listened": true },
    { "title": "Demon days", "artist": "Gorillaz", "year": 2005, "fav": true , "listened": true },
    { "title": "Takk...", "artist": "Sigur Rós", "year": 2005 },
    { "title": "En tête-à-tête", "artist": "-M-", "year": 2005 },
    { "title": "Rosenrot", "artist": "Rammstein", "year": 2005 },
    { "title": "9.0 Live", "artist": "Slipknot", "year": 2005, "listened": true, "fav": true },
    { "title": "Royal Albert Hall London May 2-3-5-6, 2005", "artist": "Cream", "year": 2005, "listened": true },
    { "title": "Darkdancer", "artist": "Les Rythmes Digitales", "year": 2005 },
    { "title": "Extraordinary Machine", "artist": "Fiona Apple", "year": 2005 },
    { "title": "Tha Carter II", "artist": "Lil Wayne", "year": 2005 },
    { "title": "The Emancipation of Mimi", "artist": "Mariah Carey", "year": 2005 },
    { "title": "Noir Désir en public", "artist": "Noir Désir", "year": 2005, "listened": true },
    { "title": "Late Registration", "artist": "Kanye West", "year": 2005 },
    { "title": "Arular", "artist": "M.I.A.", "year": 2005 },

    { "title": "Back to Black", "artist": "Amy Winehouse", "year": 2006, "listened": true },
    { "title": "Stadium Arcadium", "artist": "Red Hot Chili Peppers", "year": 2006, "listened": true },
    { "title": "Classics", "artist": "Ratatat", "year": 2006, "listened": true, "fav": true },
    { "title": "Black Holes and Revelations", "artist": "Muse", "year": 2006, "listened": true, "fav": true },
    { "title": "Whatever People Say I Am, That's What I'm Not", "artist": "Arctic Monkeys", "year": 2006, "listened": true, "fav": true },
    { "title": "808s &amp; Heartbreak", "artist": "Kanye West", "year": 2006 },
    { "title": "Donuts", "artist": "J Dilla", "year": 2006 },
    { "title": "The Village Lantern", "artist": "Blackmore's Night", "year": 2006 },
    { "title": "Morph the Cat", "artist": "Donald Fagen", "year": 2006 },
    { "title": "Continuum", "artist": "John Mayer", "year": 2006 },
    { "title": "The Black Parade", "artist": "My Chemical Romance", "year": 2006 },
    { "title": "Völkerball", "artist": "Rammstein", "year": 2006, "listened": true },

    { "title": "Favourite Worst Nightmare", "artist": "Arctic Monkeys", "year": 2007, "listened": true, "fav": true },
    { "title": "Era Vulgaris", "artist": "Queens of the Stone Age", "year": 2007, "listened": true, "fav": true },
    { "title": "HAARP (Live from Wembley Stadium)", "artist": "Muse", "year": 2007, "listened": true, "fav": true },
    { "title": "Alive 2007", "artist": "Daft Punk", "year": 2007, "listened": true, "fav": true },
    { "title": "Fancy Footwork", "artist": "Chromeo", "year": 2007, "listened": true, "fav": true },
    { "title": "Justice", "artist": "Justice", "year": 2007, "listened": true, "fav": true },
    { "title": "Graduation", "artist": "Kanye West", "year": 2007 },
    { "title": "Oracular Spectacular", "artist": "MGMT", "year": 2007, "listened": true, "fav": true },
    { "title": "Transformation", "artist": "Tal Wilkenfeld", "year": 2007 },
    { "title": "D-Sides", "artist": "Gorillaz", "year": 2007 },
    { "title": "The Good, the Bad &amp; the Queen", "artist": "The Good, the Bad &amp; the Queen", "year": 2007, "listened": true, "fav": true },
    { "title": "In Rainbows", "artist": "Radiohead", "year": 2007 },
    { "title": "Blackout", "artist": "Britney Spears", "year": 2007 },
    { "title": "Sound of Silver", "artist": "LCD Soundsystem", "year": 2007 },
    { "title": "Idealism", "artist": "Digitalism", "year": 2007, "listened": true },

    { "title": "A Cross the Universe", "artist": "Justice", "year": 2008, "listened": true, "fav": true },
    { "title": "LP3", "artist": "Ratatat", "year": 2008, "listened": true, "fav": true },
    { "title": "Tha Carter III", "artist": "Lil Wayne", "year": 2008 },
    { "title": "Walking On A Dream", "artist": "Empire of the Sun", "year": 2008, "listened": true },
    { "title": "Where the Light Is: John Mayer Live in Los Angeles", "artist": "John Mayer", "year": 2008, "listened": true },
    { "title": "Secret Voyage", "artist": "Blackmore's Night", "year": 2008 },
    { "title": "For Emma", "artist": "Bon Iver", "year": 2008 },
    { "title": "Esperanza", "artist": "Esperanza Spalding", "year": 2008 },
    { "title": "Imagine", "artist": "Armin van Buuren", "year": 2008 },
    { "title": "Bravado", "artist": "Miami Horror", "year": 2008, "listened": true, "fav": true },

    { "title": "BLACKsummers'night", "artist": "Maxwell", "year": 2009 },
    { "title": "Flashmob", "artist": "Vitalic", "year": 2009, "listened": true },
    { "title": "Wolfgang Amadeus Phoenix", "artist": "Phoenix", "year": 2009 },
    { "title": "Love 2", "artist": "Air", "year": 2009, "listened": true },
    { "title": "Elements of Life", "artist": "Tiësto", "year": 2009, "listened": true },
    { "title": "Live from Madison Square Garden", "artist": "Eric Clapton, Steve Winwood", "year": 2009 },
    { "title": "Man on the Moon: The End of the Day", "artist": "Kid Cudi", "year": 2009 },

    { "title": "Rock Dust Light Star", "artist": "Jamiroquai", "year": 2010, "fav": true, "listened": true },
    { "title": "Rated R", "artist": "Queens of the Stone Age", "year": 2010, "listened": true, "fav": true },
    { "title": "Illumination", "artist": "Miami Horror", "year": 2010, "fav": true, "listened": true },
    { "title": "My Beautiful Dark Twisted Fantasy", "artist": "Kanye West", "year": 2010 },
    { "title": "Body Talk", "artist": "Robyn", "year": 2010 },
    { "title": "TRON: Legacy", "artist": "Daft Punk", "year": 2010, "listened": true },
    { "title": "Business Casual", "artist": "Chromeo", "year": 2010, "listened": true },
    { "title": "Poised to Dominate", "artist": "TWRP", "year": 2010 },
    { "title": "A Reality Tour", "artist": "David Bowie", "year": 2010, "listened": true, "fav": true },
    { "title": "The Fall", "artist": "Gorillaz", "year": 2010, "listened": true },
    { "title": "Plastic Beach", "artist": "Gorillaz", "year": 2010, "listened": true },
    { "title": "Nightcall", "artist": "Kavinsky", "year": 2010, "listened": true },
    { "title": "LP4", "artist": "Ratatat", "year": 2010, "listened": true, "fav": true },

    { "title": "Mit Peck", "artist": "Vulfpeck", "year": 2011, "listened": true, "fav": true },
    { "title": "Congratulations", "artist": "MGMT", "year": 2011, "listened": true, "fav": true },
    { "title": "Audio, Video, Disco.", "artist": "Justice", "year": 2011, "listened": true },
    { "title": "NSFW", "artist": "Ninja Sex Party", "year": 2011, "listened": true },
    { "title": "Total", "artist": "SebastiAn", "year": 2011, "listened": true },
    { "title": "TRON: Legacy Reconfigured", "artist": "Daft Punk", "year": 2011, "listened": true },
    { "title": "Hurry Up, We're Dreaming", "artist": "M83", "year": 2011 },
    { "title": "21", "artist": "Adele", "year": 2011 },
    { "title": "Born This Way", "artist": "Lady Gaga", "year": 2011 },
    { "title": "Chief", "artist": "Eric Church", "year": 2011 },
    { "title": "Take Care", "artist": "Drake", "year": 2011 },

    { "title": "Vollmich", "artist": "Vulfpeck", "year": 2012, "listened": true, "fav": true },
    { "title": "Red", "artist": "Taylor Swift", "year": 2012 },
    { "title": "By Your Side", "artist": "Breakbot", "year": 2012, "listened": true, "fav": true },
    { "title": "Sunken Condos", "artist": "Donald Fagen", "year": 2012, "listened": true },
    { "title": "The Idler Wheel", "artist": "Fiona Apple", "year": 2012 },
    { "title": "good kid, m.A.A.d city", "artist": "Kendrick Lamar", "year": 2012, "listened": true },
    { "title": "Channel Orange", "artist": "Frank Ocean", "year": 2012 },

    { "title": "My First Car", "artist": "Vulpeck", "year": 2013, "listened": true, "fav": true },
    { "title": "...Like Clockwork", "artist": "Queens of the Stone Age", "year": 2013 },
    { "title": "Destoyer of Speakers", "artist": "F.O.O.L.", "year": 2013, "listened": true, "fav": true },
    { "title": "Starbomb", "artist": "Starbomb", "year": 2013, "listened": true, "fav": true },
    { "title": "Beyoncé", "artist": "Beyoncé", "year": 2013 },
    { "title": "Strawberries and Cream", "artist": "Ninja Sex Party", "year": 2013, "listened": true },
    { "title": "Access All Arenas", "artist": "Justice", "year": 2013 },
    { "title": "EP II", "artist": "Carpenter Brut", "year": 2013, "listened": true, "fav": true },
    { "title": "Southeastern", "artist": "Jason Isbell", "year": 2013 },
    { "title": "Modern Vampires of the City", "artist": "Vampire Weekend", "year": 2013 },
    { "title": "AM", "artist": "Arctic Monkeys", "year": 2013 },
    { "title": "Yeezus", "artist": "Kanye West", "year": 2013 },
    { "title": "Random Access Memories", "artist": "Daft Punk", "year": 2013, "listened": true, "fav": true },

    { "title": "Fugue State", "artist": "Vulpeck", "year": 2014, "listened": true, "fav": true },
    { "title": "New Game", "artist": "Nitro Fun", "year": 2014, "listened": true, "fav": true },
    { "title": "Player Select", "artist": "Starbomb", "year": 2014, "listened": true, "fav": true },
    { "title": "We Like It Here", "artist": "Snarky Puppy", "year": 2014, "listened": true, "fav": true },
    { "title": "Black Messiah", "artist": "D'Angelo and the Vanguard", "year": 2014 },
    { "title": "White Women", "artist": "Chromeo", "year": 2014, "listened": true },
    { "title": "1989", "artist": "Taylor Swift", "year": 2014 },
    { "title": "Blue Pills", "artist": "Blue Pills", "year": 2014, "listened": true },
    { "title": "Not of This World", "artist": "Adam Nitti", "year": 2014, "listened": true },
    { "title": "Vieux Frères - Partie 1", "artist": "FAUVE", "year": 2014, "listened": true },

    { "title": "To Pimp a Butterfly", "artist": "Kendrick Lamar", "year": 2015, "listened": true },
    { "title": "Magnifique", "artist": "Ratatat", "year": 2015, "listened": true, "fav": true },
    { "title": "Attitude City", "artist": "Ninja Sex Party", "year": 2015, "listened": true },
    { "title": "The Force", "artist": "Lettuce", "year": 2015, "listened": true, "fav": true },
    { "title": "All Possible Futures", "artist": "Miami Horror", "year": 2015, "listened": true, "fav": true },
    { "title": "Thrill of the Arts", "artist": "Vulfpeck", "year": 2015, "listened": true },
    { "title": "Currents", "artist": "Tame Impala", "year": 2015 },
    { "title": "Organ Freeman", "artist": "Organ Freeman", "year": 2015, "listened": true },
    { "title": "Beauty Behind the Madness", "artist": "The Weeknd", "year": 2015 },
    { "title": "If You're Reading This It's Too Late", "artist": "Drake", "year": 2015 },
    { "title": "Vieux Frères - Partie 2", "artist": "FAUVE", "year": 2015, "listened": true },

    { "title": "The Beautiful Game", "artist": "Vulfpeck", "year": 2016, "listened": true, "fav": true },
    { "title": "Still Waters", "artist": "Breakbot", "year": 2016, "listened": true, "fav": true },
    { "title": "Culcha Vulcha", "artist": "Snarky Puppy", "year": 2016, "listened": true, "fav": true },
    { "title": "Loud Hailer", "artist": "Jeff Beck", "year": 2016, "listened": true, "fav": true },
    { "title": "The Olympians", "artist": "The Olympians", "year": 2016, "listened": true, "fav": true },
    { "title": "Woman", "artist": "Justice", "year": 2016, "listened": true },
    { "title": "Lemonade", "artist": "Beyoncé", "year": 2016 },
    { "title": "150.900", "artist": "FAUVE", "year": 2016 },
    { "title": "I Still Do", "artist": "Eric Clapton", "year": 2016, "listened": true },
    { "title": "Blackstar", "artist": "David Bowie", "year": 2016, "listened": true },
    { "title": "The Weight of These Wings", "artist": "Miranda Lambert", "year": 2016 },
    { "title": "A Seat at the Table", "artist": "Solange", "year": 2016 },
    { "title": "Anti", "artist": "Rihanna", "year": 2016 },
    { "title": "Hardwired... to Self-Destruct", "artist": "Metallica", "year": 2016 },
    { "title": "Blond", "artist": "Frank Ocean", "year": 2016 },

    { "title": "Mr. Finish Line", "artist": "Vulfpeck", "year": 2017, "listened": true },
    { "title": "Villains", "artist": "Queens of the Stone Age", "year": 2017 },
    { "title": "DAMN.", "artist": "Kendrick Lamar", "year": 2017, "listened": true },
    { "title": "Golden Hour", "artist": "Kacey Musgraves", "year": 2017 },
    { "title": "Ctrl", "artist": "SZA", "year": 2017 },
    { "title": "The Shapes", "artist": "Miami Horror", "year": 2017 },
    { "title": "Melodrama", "artist": "Lorde", "year": 2017 },
    { "title": "Ladyworld", "artist": "TWRP", "year": 2017 },
    { "title": "Humanz", "artist": "Gorillaz", "year": 2017, "listened": true },
    { "title": "The Burning Spider", "artist": "Parov Stelar", "year": 2017, "listened": true, "fav": true },
    { "title": "Automaton", "artist": "Jamiroquai", "year": 2017, "fav": true, "listened": true },

    { "title": "Hill Climber", "artist": "Vulfpeck", "year": 2018, "listened": true, "fav": true },
    { "title": "Adventure", "artist": "Lydian Collective", "year": 2018, "listened": true, "fav": true },
    { "title": "The Fearless Flyers", "artist": "The Fearless Flyers", "year": 2018, "listened": true, "fav": true },
    { "title": "El Mal Querer", "artist": "Rosalìa", "year": 2018 },
    { "title": "Little Dark Age", "artist": "MGMT", "year": 2018 },
    { "title": "Merrie Land", "artist": "The Good, The Bad &amp; the Queen", "year": 2018, "listened": true },
    { "title": "Time", "artist": "Louis Cole", "year": 2018, "listened": true },
    { "title": "Cool Patrol", "artist": "Ninja Sex Party", "year": 2018, "listened": true },
    { "title": "X 100pre", "artist": "Bad Bunny", "year": 2018 },
    { "title": "The Now Now", "artist": "Gorillaz", "year": 2018 },
    { "title": "Together Through Time", "artist": "TWRP", "year": 2018 },
    { "title": "The Optimist", "artist": "Cory Wong", "year": 2018, "listened": true },

    { "title": "The Fearless Flyers II", "artist": "The Fearless Flyers", "year": 2019, "listened": true },
    { "title": "Immigrance", "artist": "Snarky Puppy", "year": 2019, "listened": true },
    { "title": "Live in Minneapolis", "artist": "Cory Wong", "year": 2019, "listened": true, "fav": true },
    { "title": "Norman Fucking Rockwell!", "artist": "Lana Del Rey", "year": 2019 },
    { "title": "Fine Line", "artist": "Harry Styles", "year": 2019 },
    { "title": "Return to Wherever", "artist": "TWRP", "year": 2019 },
    { "title": "GAS GAS GAS", "artist": "Manuel", "year": 2019, "listened": true, "fav": true },
    { "title": "When We All Fall Asleep, Where Do We Go?", "artist": "Billie Eilish", "year": 2019 },
    { "title": "Beautiful Vinyl Hunter", "artist": "Ashley Henry", "year": 2019, "listened": true },
    { "title": "The TryForce", "artist": "Starbomb", "year": 2019, "listened": true },

    { "title": "The Joy Of Music, The Jobs Of Real Estate", "artist": "Vulfpeck", "year": 2020, "listened": true },
    { "title": "Tailwinds", "artist": "The Fearless Flyers", "year": 2020, "listened": true },
    { "title": "McCartney III", "artist": "Paul McCartney", "year": 2020, "listened": true },
    { "title": "Live at the Royal Albert Hall", "artist": "Snarky Puppy", "year": 2020, "listened": true },
    { "title": "The Prophecy", "artist": "Ninja Sex Party", "year": 2020, "listened": true },
    { "title": "Anyway", "artist": "May Erlewine and the Woody Goss Band", "year": 2020, "listened": true },
    { "title": "Over the Top", "artist": "TWRP", "year": 2020 },
    { "title": "Trail Songs (Dawn)", "artist": "Cory Wong", "year": 2020, "listened": true },
    { "title": "Trail Songs: Dusk", "artist": "Cory Wong", "year": 2020, "listened": true },
    { "title": "The Striped Album", "artist": "Cory Wong", "year": 2020, "listened": true },

    { "title": "Northeast Corridor: Steely Dan Live!", "artist": "Steely Dan", "year": 2021, "listened": true, "fav": true },
    { "title": "The Nightfly: Live", "artist": "Donald Fagen", "year": 2021, "listened": true },
    { "title": "Escapades", "artist": "Gaspard Augé", "year": 2021, "listened": true },
    { "title": "Crystal Throne", "artist": "Crystal Throne", "year": 2021, "listened": true },
    { "title": "New &amp; Improved", "artist": "TWRP", "year": 2021 },

    { "title": "The Fearless Flyers III", "artist": "The Fearless Flyers", "year": 2022, "listened": true },
    { "title": "Wong's Cafe", "artist": "Cory Wong", "year": 2022, "listened": true },
    { "title": "Here We Go Jack", "artist": "Vulfmon", "year": 2022, "listened": true },
];

const albums_table = document.getElementById('albums');
var totals = {};
var number_listened = 0;
var albums_not_listened_yet = [];
albums.forEach(element => {
    const year = element['year'];

    var tr = document.createElement('tr');
    var title_td = document.createElement('td');
    title_td.innerHTML = element['title'];
    var artist_td = document.createElement('td');
    artist_td.innerHTML = element['artist'];
    var year_td = document.createElement('td');
    year_td.innerHTML = year;
    if (element['fav'] == true) {
        tr.setAttribute('class', 'fav');
    }
    var listened_td = document.createElement('td');
    listened_td.setAttribute('class', 'centered');
    if (element['listened'] == true) {
        listened_td.innerHTML = '&check;';
        number_listened += 1;
    } else {
        albums_not_listened_yet.push(element);
    }
    tr.appendChild(title_td);
    tr.appendChild(artist_td);
    tr.appendChild(year_td);
    tr.appendChild(listened_td);
    albums_table.appendChild(tr);

    const decade = Math.floor(year / 10) * 10; // 1964 -> 1960, 1992 -> 1990, etc.
    if (totals[decade] == null) {
        totals[decade] = 1;
    } else {
        totals[decade] += 1;
    } 
});

const albums_number = document.getElementById('albums-number');
albums_number.innerHTML = number_listened + ' listened to out of ' + albums.length + ' in total';

const decade_numbers = document.getElementById('decade-numbers');
for (var key in totals) {
    var li = document.createElement('li');
    li.innerHTML = key + 's: ' + totals[key];
    decade_numbers.appendChild(li);
};

const random_album_span = document.getElementById('random-album');
var random_album = albums_not_listened_yet[Math.floor(Math.random() * albums_not_listened_yet.length)];
random_album_span.innerHTML = random_album['title'] + ' - ' + random_album['artist'] + ' (' + random_album['year'] + ')';
